version: '3.3'

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=mat
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  mic_api:
    image: mintproject/mic-api-v2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - postgres

volumes:
  db_data:
